#!/usr/bin/env bash
#
# make-launcher.sh — generate a double-clickable launcher for a configured seat worktree.
#
# Emits <out>/<name>.command: a one-liner that runs seat-launch.sh against the worktree (which
# titles the window, sets identity, wires the board-loop, and launches claude). The .command is
# what you double-click; wrap it into a .app with build-apps.sh. All runtime logic stays in
# seat-launch.sh — the generated file is intentionally trivial.
#
# Usage:
#   make-launcher.sh --worktree ~/Code/nestor-sammy-dex [--out ~/Code/agents/sammy] \
#                    [--token-cmd "bash ~/Code/agents/sammy/gh-app-token.sh"]
#
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

WORKTREE="" ; OUT="" ; TOKEN_CMD=""
while [ $# -gt 0 ]; do case "$1" in
  --worktree)  WORKTREE="$2"; shift 2 ;;
  --out)       OUT="$2"; shift 2 ;;
  --token-cmd) TOKEN_CMD="$2"; shift 2 ;;
  *) echo "make-launcher: unknown arg: $1" >&2; exit 1 ;;
esac; done
[ -n "$WORKTREE" ] && [ -f "$WORKTREE/.env.local" ] || {
  echo "usage: make-launcher.sh --worktree <path-with-.env.local> [--out DIR] [--token-cmd CMD]" >&2; exit 1; }
WORKTREE="$(cd "$WORKTREE" && pwd)"

# read only the seat name (for the file name + a friendly echo); runtime reads the rest
NAME="$(. "$WORKTREE/.env.local"; printf '%s' "${SEAT_NAME:?.env.local needs SEAT_NAME}")"
KEY="$(printf '%s' "$NAME" | tr '[:upper:] ' '[:lower:]-')"
OUT="${OUT:-$(dirname "$WORKTREE")}"
mkdir -p "$OUT"
CMD="$OUT/${KEY}.command"

TOKEN_ARG=""
[ -n "$TOKEN_CMD" ] && TOKEN_ARG=" --token-cmd \"$TOKEN_CMD\""

cat > "$CMD" <<LAUNCHER
#!/usr/bin/env bash
# ${NAME} — generated by make-launcher.sh. Double-click, or: open "${KEY}.command"
exec "${HERE}/seat-launch.sh" --worktree "${WORKTREE}"${TOKEN_ARG}
LAUNCHER
chmod +x "$CMD"
echo "launcher: $CMD  →  seat-launch.sh --worktree $WORKTREE"
